### ISSUE TITLE
Log not displaying errors appropriately

### ISSUE THREAD

**Issue by Baddest-Juju** [f11894/waifu2x-chainer-GUI#2]
Using 1.0.1 (never tried 1.0) when I set up the image and the destination and what have you, and click run, nothing happens but the beep and there's no log that tells me what went wrong. And it is using the correct waifu2x-chainer path as well.

**Comment by Baddest-Juju** [comment]
Ahaaa.. okay, so a batch file appeared in the directory so I decided to run that. It's not finding ImageMagick, which I can fix pretty easily.

So I suppose the bug is that the program isn't displaying this in the Log section:
```
'magick.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Baddest-Juju** [comment]
Well, hitting another error, and unfortunately this time it's deleting the batch files almost instantaneously so I can't test those

**Comment by f11894** [comment]
The command line of waifu2x-chainer has been updated, please renew it.
Then, sorry, I do not have much program skills so it may be difficult to properly display logs.

waifu2x-chainerのコマンドラインが更新されているので新しくしてください。
それから、すみません、私はプログラムのスキルがあまりないので適切にログを表示することは難しいかもしれません。

**Comment by f11894** [comment]
Changed to issue an error message if ImageMagick is not found.

ImageMagickが見つからなければエラーメッセージを出すように変更しました。

**Comment by f11894** [comment]
Fix to display all logs output by waifu2x-chainer

waifu2x-chainerの出力するログを全て表示出来るように修正
