### ISSUE TITLE
[Request] Store config with exe

### ISSUE THREAD

**Issue by Baddest-Juju** [f11894/waifu2x-chainer-GUI#3]
When I compiled this myself (before the first release) the config was in the same directory as the program.

Now it goes to some weird directory like %LOCALAPPDATA%\waifu2x_chainer_gui\waifu2x_chainer_gui.exe_Url_h33s0ugkhdbaqauwjoiux4mk4zyz00m2\1.0.0.0\user.config

Can you change this? It's really annoying.

**Comment by f11894** [comment]
Unfortunately we can not change it.
残念ながら変更することは出来ません。
