### ISSUE TITLE
Supporting ImageMagick portable

### ISSUE THREAD

**Issue by Baddest-Juju** [f11894/waifu2x-chainer-GUI#4]
I would rather not have to install ImageMagick. I use the portable version of their software.

The DLL version does not come in a portable variety, though. Could you add support?

**Comment by f11894** [comment]
My software required ImageMagick until version 1.05, but from version 1.1 it is supposed to work with only waifu2x-chainer.

私のソフトはversion 1.05まではImageMagickを必要としていましたが、version 1.1からはwaifu2x-chainerだけで動くようになっています。

**Comment by Baddest-Juju** [comment]
Ah, okay. Thank you.

**Comment by f11894** [comment]
Sorry, it was my misunderstanding that waifu2x-chainer needs ImageMagick's DLL.
I tried it now and it worked even without it.

すみません、waifu2x-chainerがImageMagickのDLLを必要しているというのは私の勘違いでした。
今テストしたところ無くても動作しました。
